# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-09 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=4)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='validation',
        ),
    ]
