# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='origin_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('pid', models.CharField(default=-1, max_length=10)),
                ('cols', models.IntegerField(default=0)),
                ('completed_chars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='translate_queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='translated_chars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('char_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='translated_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_filename', models.CharField(max_length=128)),
                ('target_filename', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
    ]
