# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='translated_chars',
            new_name='translate_chars',
        ),
    ]
