# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='files',
            name='filepath',
            field=models.CharField(max_length=128),
        ),
    ]
