# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191108_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='translate_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('owner', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='files',
        ),
    ]
