# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191118_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='translated_chars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('char_num', models.IntegerField()),
            ],
        ),
    ]
