# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_translated_chars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='translate_chars',
        ),
    ]
