# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin_files',
            name='pid',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
