# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_origin_files_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin_files',
            name='cols',
            field=models.IntegerField(default=0),
        ),
    ]
